[package]
name = "seify-hackrfone"
version = "0.1.0"
edition = "2021"

[dependencies]
num-complex = "0.4"
thiserror = "1.0.63"
atomic_enum = "0.3.0"
# nusb = "0.1.10"
nusb = { path = "../../../nusb" }
futures-lite = "2.3.0"
tracing = "0.1.40"

[dev-dependencies]
anyhow = "1.0.86"
