[package]
name = "seify"
version = "0.23.0"
description = "Shiny Samples from your Rusty SDR"
documentation = "https://docs.rs/seify/"
edition = "2021"
homepage = "https://www.futuresdr.org"
license = "Apache-2.0"
repository = "https://github.com/FutureSDR/seify"

[features]
default = ["soapy"]
aaronia_http = ["dep:ureq"]
bladerf1 = ["dep:libbladerf-rs"]
dummy = []
hackrf = ["dep:hackrf-nusb"]
hydrasdr = ["dep:hydrasdr-rs"]
rtlsdr = ["dep:seify-rtlsdr"]
smol = ["dep:async-io", "hackrf-nusb?/smol", "hydrasdr-rs?/smol", "libbladerf-rs?/smol"]
soapy = ["dep:soapysdr"]
tokio = ["dep:tokio", "hackrf-nusb?/tokio", "hydrasdr-rs?/tokio", "libbladerf-rs?/tokio"]

[[example]]
name = "rx_typed"
required-features = ["rtlsdr"]

[dependencies]
futures = "0.3"
hackrf-nusb = { version = "0.4.0", optional = true }
hydrasdr-rs = { version = "0.5.0", optional = true }
libbladerf-rs = { version = "0.5.2", optional = true, default-features = false, features = ["bladerf1", "xb100", "xb200", "xb300"] }
log = "0.4"
nom = "8.0"
num-complex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.21"
thiserror = "2.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-io = { version = "2.6", optional = true }
once_cell = "1.21"
seify-rtlsdr = { version = "0.0.4", optional = true }
soapysdr = { version = "0.5", optional = true }
tokio = { version = "1", default-features = false, features = ["time"], optional = true }
ureq = { version = "3.3", features = ["json"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { version = "0.4", features = ["futures"] }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Navigator",
    "Usb",
    "UsbDevice",
    "UsbDeviceFilter",
    "UsbDeviceRequestOptions",
    "Window",
] }

[dev-dependencies]
clap = { version = "4.6", features = ["derive"] }
ctrlc = "3.5"
env_logger = "0.11"
gnuplot = "0.0.46"
rustfft = "6.4"
vmcircbuffer = { version = "0.0.16", features = ["sync"] }

[package.metadata.docs.rs]
no-default-features = true
features = [
    "aaronia_http",
    "bladerf1",
    "dummy",
    "hackrf",
    "hydrasdr",
    "smol",
]
